# Generated manually for the initial BTP Manager schema.
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Client', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('company_name', models.CharField(max_length=180, verbose_name='raison sociale')), ('contact_name', models.CharField(max_length=120, verbose_name='contact')), ('email', models.EmailField(blank=True, max_length=254)), ('phone', models.CharField(max_length=40)), ('address', models.TextField(blank=True))]),
        migrations.CreateModel(name='Project', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('reference', models.CharField(max_length=32, unique=True)), ('name', models.CharField(max_length=180)), ('address', models.TextField()), ('start_date', models.DateField(blank=True, null=True)), ('target_end_date', models.DateField(blank=True, null=True)), ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)), ('status', models.CharField(choices=[('SURVEY', 'Survey'), ('QUOTATION', 'Devis'), ('PURCHASE', 'Achats'), ('SITE', 'Chantier'), ('CLOSED', 'Clôturé')], default='SURVEY', max_length=16)), ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='business.client')), ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Survey', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('visit_date', models.DateField()), ('findings', models.TextField(verbose_name='constats')), ('technical_notes', models.TextField(blank=True, verbose_name='notes techniques')), ('is_validated', models.BooleanField(default=False)), ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='business.project'))]),
        migrations.CreateModel(name='Quote', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('number', models.CharField(max_length=40, unique=True)), ('amount_excl_tax', models.DecimalField(decimal_places=2, max_digits=14)), ('vat_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)), ('validity_date', models.DateField(blank=True, null=True)), ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyé'), ('APPROVED', 'Validé'), ('REJECTED', 'Refusé')], default='DRAFT', max_length=12)), ('notes', models.TextField(blank=True)), ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='business.project'))]),
        migrations.CreateModel(name='Purchase', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('reference', models.CharField(max_length=40, unique=True)), ('supplier', models.CharField(max_length=180)), ('description', models.TextField()), ('amount', models.DecimalField(decimal_places=2, max_digits=14)), ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ORDERED', 'Commandé'), ('RECEIVED', 'Reçu')], default='DRAFT', max_length=12)), ('ordered_on', models.DateField(blank=True, null=True)), ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='business.project'))]),
        migrations.CreateModel(name='Site', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('status', models.CharField(choices=[('NOT_STARTED', 'Non démarré'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé')], default='NOT_STARTED', max_length=16)), ('progress', models.PositiveSmallIntegerField(default=0)), ('started_on', models.DateField(blank=True, null=True)), ('completed_on', models.DateField(blank=True, null=True)), ('notes', models.TextField(blank=True)), ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='business.project')), ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ClosureReport', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('summary', models.TextField()), ('lessons_learned', models.TextField(blank=True)), ('final_cost', models.DecimalField(decimal_places=2, max_digits=14)), ('delivered_on', models.DateField()), ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)), ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_report', to='business.project'))]),
    ]
