# Generated by Django 5.2.17 on 2026-08-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=180, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Manager'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('SURVEY', 'Étude'), ('QUOTATION', 'Devis'), ('PURCHASE', 'Achats'), ('SITE', 'Chantier'), ('CLOSED', 'Clôturé')], default='SURVEY', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance cible'),
        ),
    ]
