# Generated by Django 5.2.17 on 2026-08-19 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_project_client_alter_project_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurereport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('SURVEY', 'Survey'), ('QUOTATION', 'Devis'), ('PURCHASE', 'Achats'), ('SITE', 'Chantier'), ('CLOSED', 'Clôturé')], default='SURVEY', max_length=16),
        ),
        migrations.AlterField(
            model_name='survey',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
