# Generated by Django 5.2.17 on 2026-08-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_quote_adjusted_amount_excl_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closurereport',
            name='final_cost',
        ),
        migrations.AddField(
            model_name='closurereport',
            name='final_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Budget Final'),
        ),
    ]
