# Generated by Django 5.2.17 on 2026-09-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_project_project_number_quoteline_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningtask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Déroulement / Détails des opérations'),
        ),
        migrations.AlterField(
            model_name='planningtask',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=120, verbose_name='Responsable / Équipe'),
        ),
        migrations.AlterField(
            model_name='planningtask',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Phase / Étape'),
        ),
        migrations.AlterField(
            model_name='projectschedule',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes / Objectifs généraux'),
        ),
    ]
