# Generated by Django 5.2.17 on 2026-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_planningtask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unité'),
        ),
    ]
