# Generated by Django 5.2.17 on 2026-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_remove_defaults_unit_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Commandé'), ('RECEIVED', 'Reçu')], default='ORDERED', max_length=12),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('SENT', 'Envoyé'), ('REJECTED', 'Refusé')], default='SENT', max_length=12),
        ),
    ]
