# Generated by Django 5.2.17 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_alter_purchase_amount_alter_quote_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(
                choices=[('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé')],
                default='ACCEPTED',
                max_length=12,
            ),
        ),
    ]