# Generated by Django 5.2.17 on 2026-09-14 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_quote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndependentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40)),
                ('amount_excl_tax', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('adjusted_amount_excl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepté'), ('REJECTED', 'Refusé')], default='ACCEPTED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='independent_quotes', to='business.client', verbose_name='Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndependentQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Unité')),
                ('designation', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='business.independentquote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
